baseURL = 'https://sensorhive.net/'
languageCode = 'en-us'
title = 'sensorhive'
theme = 'anubis'

[params]
  author = "sensorhive"
  email = "info@sensorhive.net"

  [[params.social]]
    id = "github"
    name = "sensorhive"

